In [ ]:
import pandas as pd
df=pd.read_excel("/content/MEMR-Raw Data-July.xlsx")

df.head()

,May,Unnamed: 1,For PR Calculation,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,For TA Calculation,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,Value,NaN,NaN,NaN,NaN,NaN,NaN,NaN,228.628154,NaN,...,42.778199,NaN,NaN,NaN,417.4,417.683333,414.45,0.033333,0.033333,0.033333
1,Date and Time,NaN,FPE.Meteo01.sensor_row_a17.Irradiation,FPE.Meteo01.sensor_row_b22.Irradiation,FPE.Meteo01.sensor_row_b24.Irradiation,FPE.Meteo02.sensor_row_a05.Irradiation,FPE.Meteo02.sensor_row_a06.Irradiation,FPE.Meteo02.sensor_row_b11.Irradiation,NaN,Power.Analyzer_Schneider_ION.Active Power Total,...,NaN,Inverter.01.AC_active_power,Inverter.02.AC_active_power,Inverter.03.AC_active_power,When Max Solar Irradiance is higher than 1,NaN,NaN,Inverters down time,NaN,NaN
2,NaN,NaN,[W/mÂ²],[W/mÂ²],[W/mÂ²],[W/mÂ²],[W/mÂ²],[W/mÂ²],Irradiation Tilted (kWh/m2),NaN,...,Average Module Temp (C°),[kW],[kW],[kW],Inverter 1 useful time,Inverter 2 useful time,Inverter 3 useful time,Inverter 1 down time,Inverter 2 down time,Inverter 3 down time
3,01.07.2020 00:00:00,NaN,0.5,0,0,0.2,0.5,0.2,0,25.683,...,NaN,0,0,0,0,0,0,0.99992,0.99992,0.99992
4,01.07.2020 00:01:00,NaN,0.4,0,0.1,0.2,0.5,0.2,0,26.633,...,,0,0,0,0,0,0,NaN,NaN,NaN

In [ ]:
import pandas as pd

df = pd.read_excel(
    "/content/MEMR-Raw Data-July.xlsx",
    skiprows=3   # row with the real column names
)

df.head()

,Unnamed: 0,Unnamed: 1,[W/mÂ²],[W/mÂ²].1,[W/mÂ²].2,[W/mÂ²].3,[W/mÂ²].4,[W/mÂ²].5,Irradiation Tilted (kWh/m2),Unnamed: 9,...,Average Module Temp (C°),[kW],[kW].1,[kW].2,Inverter 1 useful time,Inverter 2 useful time,Inverter 3 useful time,Inverter 1 down time,Inverter 2 down time,Inverter 3 down time
0,01.07.2020 00:00:00,NaN,0.5,0.0,0.0,0.2,0.5,0.2,0.0,25.683,...,NaN,0.0,0.0,0.0,0,0,0,0.99992,0.99992,0.99992
1,01.07.2020 00:01:00,NaN,0.4,0.0,0.1,0.2,0.5,0.2,0.0,26.633,...,,0.0,0.0,0.0,0,0,0,NaN,NaN,NaN
2,01.07.2020 00:02:00,NaN,0.4,0.0,0.0,0.1,0.5,0.2,0.0,26.400,...,,0.0,0.0,0.0,0,0,0,NaN,NaN,NaN
3,01.07.2020 00:03:00,NaN,0.4,0.0,0.1,0.2,0.5,0.2,0.0,26.000,...,,0.0,0.0,0.0,0,0,0,NaN,NaN,NaN
4,01.07.2020 00:04:00,NaN,0.4,0.0,0.0,0.1,0.5,0.1,0.0,26.000,...,,0.0,0.0,0.0,0,0,0,NaN,NaN,NaN

In [ ]:
df.columns = [
    "datetime",
    "col_unused",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6",
    "irradiation_tilted",
    "power_analyzer",
    "generated_yield",
    "module_temp",
    "avg_module_temp",
    "1",
    "2",
    "30",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
]

In [ ]:
df = df[[
    "datetime",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6"
]]
df

,datetime,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6
0,01.07.2020 00:00:00,0.5,0.0,0.0,0.2,0.5,0.2
1,01.07.2020 00:01:00,0.4,0.0,0.1,0.2,0.5,0.2
2,01.07.2020 00:02:00,0.4,0.0,0.0,0.1,0.5,0.2
3,01.07.2020 00:03:00,0.4,0.0,0.1,0.2,0.5,0.2
4,01.07.2020 00:04:00,0.4,0.0,0.0,0.1,0.5,0.1
...,...,...,...,...,...,...,...
44635,31.07.2020 23:55:00,0.3,0.0,0.0,0.0,0.4,0.1
44636,31.07.2020 23:56:00,0.3,0.0,0.0,0.0,0.4,0.1
44637,31.07.2020 23:57:00,0.3,0.0,0.0,0.0,0.3,0.1
44638,31.07.2020 23:58:00,0.3,0.0,0.0,0.0,0.3,0.1
44639,31.07.2020 23:59:00,0.3,0.0,0.0,0.0,0.4,0.1

In [ ]:
df["datetime"] = pd.to_datetime(df["datetime"], format='%d.%m.%Y %H:%M:%S')
df = df.set_index("datetime")

In [ ]:
df

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6
datetime,,,,,,
2020-07-01 00:00:00,0.5,0.0,0.0,0.2,0.5,0.2
2020-07-01 00:01:00,0.4,0.0,0.1,0.2,0.5,0.2
2020-07-01 00:02:00,0.4,0.0,0.0,0.1,0.5,0.2
2020-07-01 00:03:00,0.4,0.0,0.1,0.2,0.5,0.2
2020-07-01 00:04:00,0.4,0.0,0.0,0.1,0.5,0.1
...,...,...,...,...,...,...
2020-07-31 23:55:00,0.3,0.0,0.0,0.0,0.4,0.1
2020-07-31 23:56:00,0.3,0.0,0.0,0.0,0.4,0.1
2020-07-31 23:57:00,0.3,0.0,0.0,0.0,0.3,0.1
2020-07-31 23:58:00,0.3,0.0,0.0,0.0,0.3,0.1
2020-07-31 23:59:00,0.3,0.0,0.0,0.0,0.4,0.1

In [ ]:
df["irradiance_avg"] = df.mean(axis=1)
df

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-07-01 00:00:00,0.5,0.0,0.0,0.2,0.5,0.2,0.233333
2020-07-01 00:01:00,0.4,0.0,0.1,0.2,0.5,0.2,0.233333
2020-07-01 00:02:00,0.4,0.0,0.0,0.1,0.5,0.2,0.200000
2020-07-01 00:03:00,0.4,0.0,0.1,0.2,0.5,0.2,0.233333
2020-07-01 00:04:00,0.4,0.0,0.0,0.1,0.5,0.1,0.183333
...,...,...,...,...,...,...,...
2020-07-31 23:55:00,0.3,0.0,0.0,0.0,0.4,0.1,0.133333
2020-07-31 23:56:00,0.3,0.0,0.0,0.0,0.4,0.1,0.133333
2020-07-31 23:57:00,0.3,0.0,0.0,0.0,0.3,0.1,0.116667
2020-07-31 23:58:00,0.3,0.0,0.0,0.0,0.3,0.1,0.116667
2020-07-31 23:59:00,0.3,0.0,0.0,0.0,0.4,0.1,0.133333

In [ ]:
df.describe()

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
count,44640.000000,44640.000000,44640.000000,44178.000000,43797.000000,43858.000000,44640.000000
mean,314.194944,310.356736,320.353737,316.254826,316.916031,313.637113,314.890897
std,379.944540,377.698199,384.009548,376.276756,377.533602,376.132645,378.606041
min,0.000000,0.000000,0.000000,0.000000,0.100000,0.000000,0.000000
25%,0.500000,0.000000,0.100000,0.100000,0.500000,0.200000,0.216667
50%,41.500000,42.000000,50.000000,58.800000,56.800000,54.700000,51.450000
75%,687.200000,679.800000,698.525000,684.675000,685.800000,679.975000,685.970833
max,1047.200000,1038.700000,1055.800000,1057.400000,1052.000000,1045.700000,1048.416667

In [ ]:
df.shape

(44640, 7)

In [ ]:
df = df.dropna(how="all")
df.shape

(44640, 7)

In [ ]:
print("First Sensor values missing values: ",df["irr_sensor_1"].isnull().sum(),"\n")
print("Second Sensor values missing values: ",df["irr_sensor_2"].isnull().sum(),"\n")
print("Third Sensor values missing values: ",df["irr_sensor_3"].isnull().sum(),"\n")
print("Fourth Sensor values missing values: ",df["irr_sensor_4"].isnull().sum(),"\n")
print("Fifth Sensor values missing values: ",df["irr_sensor_5"].isnull().sum(),"\n")
print("Sixth Sensor values missing values: ",df["irr_sensor_6"].isnull().sum(),"\n")
print("Average Irradiance values missing values: ",df["irradiance_avg"].isnull().sum())

First Sensor values missing values:  0

Second Sensor values missing values:  0

Third Sensor values missing values:  0

Fourth Sensor values missing values:  462

Fifth Sensor values missing values:  843

Sixth Sensor values missing values:  782

Average Irradiance values missing values:  0

In [ ]:
sensor_cols = [
    "irr_sensor_1", "irr_sensor_2", "irr_sensor_3",
    "irr_sensor_4", "irr_sensor_5", "irr_sensor_6",
    "irradiance_avg"
]

def count_sensor_outliers(df, columns):
    outlier_counts = {}
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        outlier_counts[col] = df[(df[col] < lower) | (df[col] > upper)].shape[0]
    return outlier_counts

outliers = count_sensor_outliers(df, sensor_cols)
print("Number of outliers per sensor:\n", outliers)

Number of outliers per sensor:
 {'irr_sensor_1': 0, 'irr_sensor_2': 0, 'irr_sensor_3': 0, 'irr_sensor_4': 0, 'irr_sensor_5': 0, 'irr_sensor_6': 0, 'irradiance_avg': 0}

In [ ]:
import pandas as pd

df6= pd.read_excel(
    "/content/MEMR-Raw Data-June.xlsx",
    skiprows=3   # row with the real column names
)



df6.columns = [
    "datetime",
    "col_unused",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6",
    "irradiation_tilted",
    "power_analyzer",
    "generated_yield",
    "module_temp",
    "avg_module_temp",
    "1",
    "2",
    "30",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
]

df6

,datetime,col_unused,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,...,avg_module_temp,1,2,30,4,5,6,7,8,9
0,01.06.2020 00:00:00,NaN,0.3,0.0,0.0,0.1,0.3,0.1,0.0,16.0,...,25.35,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0
1,01.06.2020 00:01:00,NaN,0.3,0.0,0.0,0.1,0.3,0.1,0.0,16.0,...,25.3,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,01.06.2020 00:02:00,NaN,0.3,0.0,0.0,0.2,0.3,0.1,0.0,16.0,...,25.23,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3,01.06.2020 00:03:00,NaN,0.3,0.0,0.0,0.2,0.3,0.0,0.0,16.0,...,25.18,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,01.06.2020 00:04:00,NaN,0.3,0.0,0.0,0.1,0.3,0.1,0.0,16.0,...,25.12,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
44637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
44638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
44639,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
44640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN

In [ ]:
df6["datetime"] = pd.to_datetime(df6["datetime"], format='%d.%m.%Y %H:%M:%S')
df6 = df6.set_index("datetime")

In [ ]:
df6 = df6[[
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6"
]]

In [ ]:
df6['irradiance_avg'] = df6.mean(axis=1, skipna=True)

print("First Sensor values missing values: ",df6["irr_sensor_1"].isnull().sum(),"\n")
print("Second Sensor values missing values: ",df6["irr_sensor_2"].isnull().sum(),"\n")
print("Third Sensor values missing values: ",df6["irr_sensor_3"].isnull().sum(),"\n")
print("Fourth Sensor values missing values: ",df6["irr_sensor_4"].isnull().sum(),"\n")
print("Fifth Sensor values missing values: ",df6["irr_sensor_5"].isnull().sum(),"\n")
print("Sixth Sensor values missing values: ",df6["irr_sensor_6"].isnull().sum(),"\n")
print("Average Irradiance values missing values: ",df6["irradiance_avg"].isnull().sum())

First Sensor values missing values:  1441

Second Sensor values missing values:  1441

Third Sensor values missing values:  1441

Fourth Sensor values missing values:  1864

Fifth Sensor values missing values:  2034

Sixth Sensor values missing values:  2003

Average Irradiance values missing values:  1441

In [ ]:
sensor_cols = [
    "irr_sensor_1", "irr_sensor_2", "irr_sensor_3",
    "irr_sensor_4", "irr_sensor_5", "irr_sensor_6",
    "irradiance_avg"
]

def count_sensor_outliers(df, columns):
    outlier_counts = {}
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        outlier_counts[col] = df[(df[col] < lower) | (df[col] > upper)].shape[0]
    return outlier_counts

outliers = count_sensor_outliers(df6, sensor_cols)
print("Number of outliers per sensor:\n", outliers)

Number of outliers per sensor:
 {'irr_sensor_1': 0, 'irr_sensor_2': 0, 'irr_sensor_3': 0, 'irr_sensor_4': 0, 'irr_sensor_5': 0, 'irr_sensor_6': 0, 'irradiance_avg': 0}

In [ ]:
df6.shape

(44641, 7)

In [ ]:
df6 = df6.dropna(how="all")
df6.shape

(43200, 7)

In [ ]:
print(df.index.dtype)

datetime64[ns]

datetime
0 days 00:01:00    44639
Name: count, dtype: int64

In [ ]:
full_range = pd.date_range(df.index.min(), df.index.max(), freq="1min")

missing = full_range.difference(df.index)

len(missing)

0

In [ ]:
df_hourly = df.resample("1H").mean()
df_hourly.shape

(744, 7)

In [ ]:
df_hourly = df_hourly[df_hourly.mean(axis=1) > 20]

In [ ]:
df_hourly.shape
df_hourly

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-07-01 06:00:00,33.348333,46.365000,59.586667,70.028571,76.067500,62.622222,55.740722
2020-07-01 07:00:00,208.160000,224.721667,255.683333,291.447273,306.649020,270.498077,253.027361
2020-07-01 08:00:00,456.333333,470.136667,501.636667,522.261017,534.371186,510.715000,499.633194
2020-07-01 09:00:00,682.078333,692.646667,720.916667,733.718868,739.279167,717.131915,714.813722
2020-07-01 10:00:00,851.666667,857.135000,881.583333,896.196296,904.180769,888.728846,876.012917
...,...,...,...,...,...,...,...
2020-07-31 14:00:00,877.178333,852.156667,866.135000,805.813333,822.938333,829.505000,842.287778
2020-07-31 15:00:00,731.925000,699.453333,716.023333,655.668333,665.363333,672.233333,690.111111
2020-07-31 16:00:00,533.938333,495.920000,515.741667,462.711667,464.460000,469.611667,490.397222
2020-07-31 17:00:00,289.738333,253.383333,273.805000,242.275000,235.808333,237.835000,255.474167
2020-07-31 18:00:00,84.621667,56.316667,74.990000,72.960000,63.315000,65.536667,69.623333

In [ ]:
print(df6.index.dtype)
df6 = df6.sort_index()
df6.index.to_series().diff().value_counts()

datetime64[ns]

datetime
0 days 00:01:00    43199
Name: count, dtype: int64

In [ ]:
full_range = pd.date_range(df.index.min(), df6.index.max(), freq="1min")

missing6 = full_range.difference(df6.index)

len(missing6)

0

In [ ]:
df6_hourly = df6.resample("1H").mean()
df6_hourly.shape

(720, 7)

In [ ]:
df6_hourly = df6_hourly[df6_hourly.mean(axis=1) > 20]

In [ ]:
df6_hourly.shape
df6_hourly

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-06-01 06:00:00,53.515000,65.055000,76.843333,85.708333,93.260000,82.495000,76.146111
2020-06-01 07:00:00,222.061667,232.023333,260.448333,286.641667,292.835000,272.923333,261.155556
2020-06-01 08:00:00,458.563333,465.343333,500.151667,525.641667,532.103333,513.946667,499.291667
2020-06-01 09:00:00,673.463333,675.321667,709.126667,730.691667,733.742373,720.225424,707.265972
2020-06-01 10:00:00,841.096667,837.505000,868.223333,886.628814,886.783051,878.330508,865.627500
...,...,...,...,...,...,...,...
2020-06-30 14:00:00,888.355000,863.700000,874.408333,844.675000,827.901667,828.933333,854.662222
2020-06-30 15:00:00,739.418333,707.056667,720.923333,690.303333,668.755000,669.808333,699.377500
2020-06-30 16:00:00,534.771667,497.141667,515.056667,487.870000,463.216667,462.845000,493.483611
2020-06-30 17:00:00,304.246667,264.913333,287.251667,271.835000,246.530000,243.310000,269.681111
2020-06-30 18:00:00,91.835000,57.276667,80.663333,85.506667,65.878333,66.598333,74.626389

In [ ]:
df_combined = pd.concat([df6_hourly, df_hourly])
df_combined

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-06-01 06:00:00,53.515000,65.055000,76.843333,85.708333,93.260000,82.495000,76.146111
2020-06-01 07:00:00,222.061667,232.023333,260.448333,286.641667,292.835000,272.923333,261.155556
2020-06-01 08:00:00,458.563333,465.343333,500.151667,525.641667,532.103333,513.946667,499.291667
2020-06-01 09:00:00,673.463333,675.321667,709.126667,730.691667,733.742373,720.225424,707.265972
2020-06-01 10:00:00,841.096667,837.505000,868.223333,886.628814,886.783051,878.330508,865.627500
...,...,...,...,...,...,...,...
2020-07-31 14:00:00,877.178333,852.156667,866.135000,805.813333,822.938333,829.505000,842.287778
2020-07-31 15:00:00,731.925000,699.453333,716.023333,655.668333,665.363333,672.233333,690.111111
2020-07-31 16:00:00,533.938333,495.920000,515.741667,462.711667,464.460000,469.611667,490.397222
2020-07-31 17:00:00,289.738333,253.383333,273.805000,242.275000,235.808333,237.835000,255.474167
2020-07-31 18:00:00,84.621667,56.316667,74.990000,72.960000,63.315000,65.536667,69.623333

In [ ]:
df_combined = df_combined.sort_index()
df_combined.head()

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-06-01 06:00:00,53.515000,65.055000,76.843333,85.708333,93.260000,82.495000,76.146111
2020-06-01 07:00:00,222.061667,232.023333,260.448333,286.641667,292.835000,272.923333,261.155556
2020-06-01 08:00:00,458.563333,465.343333,500.151667,525.641667,532.103333,513.946667,499.291667
2020-06-01 09:00:00,673.463333,675.321667,709.126667,730.691667,733.742373,720.225424,707.265972
2020-06-01 10:00:00,841.096667,837.505000,868.223333,886.628814,886.783051,878.330508,865.627500

In [ ]:
df_combined.tail()

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg
datetime,,,,,,,
2020-07-31 14:00:00,877.178333,852.156667,866.135000,805.813333,822.938333,829.505000,842.287778
2020-07-31 15:00:00,731.925000,699.453333,716.023333,655.668333,665.363333,672.233333,690.111111
2020-07-31 16:00:00,533.938333,495.920000,515.741667,462.711667,464.460000,469.611667,490.397222
2020-07-31 17:00:00,289.738333,253.383333,273.805000,242.275000,235.808333,237.835000,255.474167
2020-07-31 18:00:00,84.621667,56.316667,74.990000,72.960000,63.315000,65.536667,69.623333

In [ ]:
df_combined.index.duplicated().sum()

np.int64(0)

The following cell is the cell with the essential steps done for each file before concatination

In [ ]:
import pandas as pd
#reading the file with skipping the few unneccesary headers and rows

df = pd.read_excel(
    "/content/MEMR-Raw Data-July.xlsx",
    skiprows=3   # row with the real column names
)



#  then renaming the columns to work with the 6 sensors, here the most important columns are the solar irradiance sensors  and datetime hence naming the others was
#just to proceed

df.columns = [
    "datetime",
    "col_unused",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6",
    "irradiation_tilted",
    "power_analyzer",
    "generated_yield",
    "module_temp",
    "avg_module_temp",
    "1",
    "2",
    "30",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
]


#then choosing the essential columns
 df = df[[
    "datetime",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6"
]]

# making the datetime column as index with correct format

df["datetime"] = pd.to_datetime(df["datetime"], format='%d.%m.%Y %H:%M:%S')
df = df.set_index("datetime")



# taking the average of the sensors and ignore the missing sensor readings:
df['irradiance_avg'] = df6.mean(axis=1, skipna=True)

#dropping the FULLY empty rows since the excel file can read completely empty rows

df = df.dropna(how="all")

# sorting the time index in the excel file and making it ready to be used in time series
df = df.sort_index()
df.index.to_series().diff().value_counts()

# the resampling step to hourly be taking the avrage readings for one each minutein a certain hour and presenting it in that hour
df_hourly = df.resample("1H").mean()

# the official threshold for solar irradiance allowed noise readings at night and flowing electricity ( threshold may be changed)
df_hourly = df_hourly[df_hourly.mean(axis=1) > 20]

# the combining step between each resampled dataset
df_combined = pd.concat([df6_hourly, df_hourly])

# sorting the combined dataset
df_combined = df_combined.sort_index()


# Dahleh's work with the fixed Data

In [ ]:
import pandas as pd
import glob
import os


files = glob.glob("*.xlsx")
output_file = "trial_display_file.xlsx"

month_order = {
    "january": 1,
    "february": 2,
    "march": 3,
    "april": 4,
    "may": 5,
    "june": 6,
    "july": 7,
    "august": 8,
    "september": 9,
    "october": 10,
    "november": 11,
    "december": 12
}

files = sorted(
    files,
    key=lambda f: next(
        (month_order[m] for m in month_order if m in os.path.basename(f).lower()),
        99
    )
)

print("Files found:")
for f in files:
    print("-", os.path.basename(f))

df_merged = pd.DataFrame()

for file in files:
    filename = os.path.basename(file)
    print(f"\nReading: {filename}")

    df = pd.read_excel(file, skiprows=3)

    df.columns = [
    "datetime",
    "col_unused",
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6",
    "irradiation_tilted",
    "power_analyzer",
    "generated_yield",
    "avg_module_temp",
    "module_temp",
    "1",
    "2",
    "30",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
]

    df = df[[
        "datetime",
        "irr_sensor_1",
        "irr_sensor_2",
        "irr_sensor_3",
        "irr_sensor_4",
        "irr_sensor_5",
        "irr_sensor_6",
        "irradiation_tilted",
        "power_analyzer",
        "generated_yield",
        "avg_module_temp",
    ]]

    df["datetime"] = pd.to_datetime(
        df["datetime"],
        format="%d.%m.%Y %H:%M:%S",
        errors="coerce"
    )

    df = df.dropna(subset=["datetime"])
    df = df.set_index("datetime")

    # Convert relevant columns to numeric, coercing errors to NaN
    numeric_cols = [
        "irr_sensor_1", "irr_sensor_2", "irr_sensor_3",
        "irr_sensor_4", "irr_sensor_5", "irr_sensor_6",
        "irradiation_tilted", "power_analyzer", "generated_yield",
        "avg_module_temp"
    ]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # Calculate the average irradiance for the raw data
    df["irradiance_avg"] = df[[
        "irr_sensor_1", "irr_sensor_2", "irr_sensor_3",
        "irr_sensor_4", "irr_sensor_5", "irr_sensor_6"
    ]].mean(axis=1, skipna=True)

    # Resample to hourly mean after ensuring all columns are numeric
    df = df.resample("15T").mean()

    # Filter out hours where the overall mean irradiance is below a threshold
    # This line depends on 'irradiance_avg' being present and numeric.
    # If 'irradiance_avg' is not critical for the filter, consider using another column or the mean of other columns.
    #df = df[df["irradiance_avg"] > 50] ## remv

    df["source_file"] = filename

    df_merged = pd.concat([df_merged, df], axis=0)

    print("Current merged shape:", df_merged.shape)

df_merged = df_merged.sort_index()
df_merged.to_excel(output_file)

print("\nFinal merged shape:", df_merged.shape)
print("Saved to:", output_file)

display(df_merged.head())
display(df_merged.tail())

Files found:
- April 2020 fixed.xlsx
- May 2020 Fixed (1).xlsx

Reading: April 2020 fixed.xlsx

/tmp/ipykernel_1654/2622561906.py:109: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df = df.resample("15T").mean()

Current merged shape: (2881, 12)

Reading: May 2020 Fixed (1).xlsx

/tmp/ipykernel_1654/2622561906.py:109: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  df = df.resample("15T").mean()

Current merged shape: (5858, 12)

Final merged shape: (5858, 12)
Saved to: trial_display_file.xlsx

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file
datetime,,,,,,,,,,,,
2020-04-01 00:00:00,0.078571,0.0,0.0,0.0,0.0,0.0,0.0,16.232143,0.0,18.240714,0.013095,April 2020 fixed.xlsx
2020-04-01 00:15:00,0.086667,0.0,0.0,0.0,0.0,0.0,0.0,19.434400,0.0,17.866000,0.014444,April 2020 fixed.xlsx
2020-04-01 00:30:00,0.086667,0.0,0.0,0.0,0.0,0.0,0.0,20.278867,0.0,17.906667,0.014444,April 2020 fixed.xlsx
2020-04-01 00:45:00,0.046667,0.0,0.0,0.0,0.0,0.0,0.0,19.122267,0.0,17.767333,0.007778,April 2020 fixed.xlsx
2020-04-01 01:00:00,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,18.954467,0.0,17.115333,0.000000,April 2020 fixed.xlsx

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file
datetime,,,,,,,,,,,,
2020-05-31 23:00:00,0.113333,0.0,0.0,0.0,0.093333,0.026667,0.0,15.815533,0.0,22.908667,0.038889,May 2020 Fixed (1).xlsx
2020-05-31 23:15:00,0.113333,0.0,0.0,0.0,0.080000,0.073333,0.0,15.742200,0.0,22.718000,0.044444,May 2020 Fixed (1).xlsx
2020-05-31 23:30:00,0.106667,0.0,0.0,0.0,0.086667,0.053333,0.0,15.521133,0.0,22.433333,0.041111,May 2020 Fixed (1).xlsx
2020-05-31 23:45:00,0.100000,0.0,0.0,0.0,0.073333,0.053333,0.0,15.787733,0.0,22.196667,0.037778,May 2020 Fixed (1).xlsx
2020-06-01 00:00:00,0.100000,0.0,0.0,0.0,0.000000,0.100000,0.0,18.000000,0.0,22.070000,0.033333,May 2020 Fixed (1).xlsx

In [ ]:
import pandas as pd
df_merged=pd.read_excel("/content/Fifteen_minutes_merged_2022_data.xlsx")

In [ ]:
# Convert the 'datetime' column to datetime objects
df_merged['datetime'] = pd.to_datetime(df_merged['datetime'])

# Set the 'datetime' column as the index
df_merged= df_merged.set_index('datetime')

# Display the head of the DataFrame to show the new index
print("irr_df head after setting 'datetime' as index:")
print(df_merged.head())

irr_df head after setting 'datetime' as index:
                     irr_sensor_1  irr_sensor_2  irr_sensor_3  irr_sensor_4  \
datetime
2022-01-01 00:00:00           0.0           0.0           0.0           0.0
2022-01-01 00:15:00           0.0           0.0           0.0           0.0
2022-01-01 00:30:00           0.0           0.0           0.0           0.0
2022-01-01 00:45:00           0.0           0.0           0.0           0.0
2022-01-01 01:00:00           0.0           0.0           0.0           0.0

                     irr_sensor_5  irr_sensor_6  irradiation_tilted  \
datetime
2022-01-01 00:00:00           0.0           0.0                 0.0
2022-01-01 00:15:00           0.0           0.0                 0.0
2022-01-01 00:30:00           0.0           0.0                 0.0
2022-01-01 00:45:00           0.0           0.0                 0.0
2022-01-01 01:00:00           0.0           0.0                 0.0

                     power_analyzer  generated_yield  avg_module_temp  \
datetime
2022-01-01 00:00:00       14.723333              0.0        13.208667
2022-01-01 00:15:00       13.998867              0.0        13.174667
2022-01-01 00:30:00       13.975533              0.0        13.272000
2022-01-01 00:45:00       13.981133              0.0        13.196000
2022-01-01 01:00:00       13.839933              0.0        13.014667

                     irradiance_avg              source_file
datetime
2022-01-01 00:00:00             0.0  January 2022 fixed.xlsx
2022-01-01 00:15:00             0.0  January 2022 fixed.xlsx
2022-01-01 00:30:00             0.0  January 2022 fixed.xlsx
2022-01-01 00:45:00             0.0  January 2022 fixed.xlsx
2022-01-01 01:00:00             0.0  January 2022 fixed.xlsx

In [ ]:
df_merged = df_merged.sort_index()

In [ ]:
import pandas as pd
# Make sure index is datetime

#df_merged.index = pd.to_datetime(df_merged.index)

# Work on a copy to avoid warnings
irr_df = pd.read_excel("/content/Fifteen_minutes_merged_2020-2022.xlsx")

irr_df = irr_df.set_index("datetime")
irr_df.index = pd.to_datetime(irr_df.index)

irr_df=irr_df[[
     'irr_sensor_1', 'irr_sensor_2', 'irr_sensor_3',
       'irr_sensor_4', 'irr_sensor_5', 'irr_sensor_6',
       'irradiance_avg', 'source_file'
]]

irr_cols = [
    "irr_sensor_1",
    "irr_sensor_2",
    "irr_sensor_3",
    "irr_sensor_4",
    "irr_sensor_5",
    "irr_sensor_6"
]

# 1️⃣ Drop rows where ALL sensors are NaN
irr_df = irr_df.dropna(subset=irr_cols, how="all")

# 2️⃣ Fill irradiance_avg NaNs
irr_df["irradiance_avg"] = irr_df["irradiance_avg"].fillna(0)

# 3️⃣ Create masks (NOW it works)
day_mask = (irr_df.index.hour >= 6) & (irr_df.index.hour < 18)
night_mask = ~day_mask

# 4️⃣ Fill daytime NaNs with irradiance_avg
for col in irr_cols:
    irr_df.loc[day_mask & irr_df[col].isna(), col] = irr_df.loc[day_mask, "irradiance_avg"]

# 5️⃣ Fill nighttime NaNs with 0
irr_df.loc[night_mask, irr_cols] = irr_df.loc[night_mask, irr_cols].fillna(0)

In [ ]:
irr_df.head()

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg,source_file
datetime,,,,,,,,
2020-03-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,March 2020 Fixed.xlsx
2020-03-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,March 2020 Fixed.xlsx
2020-03-01 00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,March 2020 Fixed.xlsx
2020-03-01 00:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,March 2020 Fixed.xlsx
2020-03-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,March 2020 Fixed.xlsx

In [ ]:
irr_df.tail(50)

,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiance_avg,source_file
datetime,,,,,,,,
2022-02-24 11:30:00,931.646667,956.586667,918.420000,907.760000,908.380000,946.026667,928.136667,febraury 2022 fixed.xlsx
2022-02-24 11:45:00,936.340000,958.560000,920.626667,910.986667,909.300000,948.100000,930.652222,febraury 2022 fixed.xlsx
2022-02-24 12:00:00,928.000000,948.780000,910.293333,900.826667,897.560000,942.393333,921.308889,febraury 2022 fixed.xlsx
2022-02-24 12:15:00,840.046667,849.340000,814.960000,820.540000,811.046667,861.006667,832.823333,febraury 2022 fixed.xlsx
2022-02-24 12:30:00,867.073333,871.486667,838.366667,842.193333,838.260000,880.920000,856.383333,febraury 2022 fixed.xlsx
2022-02-24 12:45:00,784.173333,785.093333,755.540000,741.680000,735.506667,775.320000,762.885556,febraury 2022 fixed.xlsx
2022-02-24 13:00:00,853.813333,863.986667,828.493333,815.773333,805.226667,854.346667,836.940000,febraury 2022 fixed.xlsx
2022-02-24 13:15:00,826.473333,834.280000,799.380000,785.933333,774.253333,822.946667,807.211111,febraury 2022 fixed.xlsx
2022-02-24 13:30:00,794.120000,799.900000,765.580000,751.306667,738.046667,786.753333,772.617778,febraury 2022 fixed.xlsx
2022-02-24 13:45:00,756.340000,759.973333,726.760000,712.000000,697.406667,745.873333,733.058889,febraury 2022 fixed.xlsx
2022-02-24 14:00:00,713.133333,714.666667,682.586667,667.626667,651.766667,699.446667,688.204444,febraury 2022 fixed.xlsx
2022-02-24 14:15:00,665.240000,664.620000,633.986667,619.273333,602.153333,648.720000,638.998889,febraury 2022 fixed.xlsx
2022-02-24 14:30:00,600.753333,598.713333,569.973333,556.746667,538.800000,582.980000,574.661111,febraury 2022 fixed.xlsx
2022-02-24 14:45:00,549.253333,545.700000,518.193333,504.633333,486.206667,529.066667,522.175556,febraury 2022 fixed.xlsx
2022-02-24 15:00:00,484.353333,478.833333,453.986667,441.440000,422.593333,462.906667,457.352222,febraury 2022 fixed.xlsx
2022-02-24 15:15:00,413.606667,406.560000,385.246667,374.166667,355.940000,391.926667,387.907778,febraury 2022 fixed.xlsx
2022-02-24 15:30:00,355.353333,347.266667,328.293333,317.966667,300.106667,333.053333,330.340000,febraury 2022 fixed.xlsx
2022-02-24 15:45:00,280.826667,271.880000,256.686667,249.520000,233.546667,260.280000,258.790000,febraury 2022 fixed.xlsx
2022-02-24 16:00:00,209.826667,201.786667,191.013333,186.566667,173.226667,193.966667,192.731111,febraury 2022 fixed.xlsx
2022-02-24 16:15:00,153.326667,145.993333,138.773333,136.720000,126.073333,141.353333,140.373333,febraury 2022 fixed.xlsx
2022-02-24 16:30:00,94.733333,89.760000,86.660000,87.546667,80.773333,89.293333,88.127778,febraury 2022 fixed.xlsx
2022-02-24 16:45:00,47.353333,44.140000,44.926667,46.400000,43.800000,46.766667,45.564444,febraury 2022 fixed.xlsx
2022-02-24 17:00:00,17.220000,16.766667,17.026667,18.220000,17.840000,18.426667,17.583333,febraury 2022 fixed.xlsx
2022-02-24 17:15:00,4.166667,3.713333,4.006667,4.440000,4.500000,4.626667,4.242222,febraury 2022 fixed.xlsx
2022-02-24 17:30:00,0.553333,0.226667,0.360000,0.546667,0.706667,0.753333,0.524444,febraury 2022 fixed.xlsx
2022-02-24 17:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.006667,0.001111,febraury 2022 fixed.xlsx
2022-02-24 18:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 18:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 18:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 18:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 19:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 19:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 19:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 19:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 20:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 20:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 20:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 20:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 21:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 21:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 21:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 21:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 22:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 22:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 22:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 22:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 23:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 23:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 23:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx
2022-02-24 23:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,febraury 2022 fixed.xlsx

In [ ]:
irr_df.isnull().sum()

irr_sensor_1      0
irr_sensor_2      0
irr_sensor_3      0
irr_sensor_4      0
irr_sensor_5      0
irr_sensor_6      0
irradiance_avg    0
source_file       0
dtype: int64

In [ ]:
irr_df.index

DatetimeIndex(['2020-03-01 00:00:00', '2020-03-01 00:15:00',
               '2020-03-01 00:30:00', '2020-03-01 00:45:00',
               '2020-03-01 01:00:00', '2020-03-01 01:15:00',
               '2020-03-01 01:30:00', '2020-03-01 01:45:00',
               '2020-03-01 02:00:00', '2020-03-01 02:15:00',
               ...
               '2022-02-24 21:30:00', '2022-02-24 21:45:00',
               '2022-02-24 22:00:00', '2022-02-24 22:15:00',
               '2022-02-24 22:30:00', '2022-02-24 22:45:00',
               '2022-02-24 23:00:00', '2022-02-24 23:15:00',
               '2022-02-24 23:30:00', '2022-02-24 23:45:00'],
              dtype='datetime64[ns]', name='datetime', length=69545, freq=None)

In [ ]:
irr_df.to_excel("Fifteen_minutes_irradiance_dataset_2020-2022.xlsx")

# Newly added power and efficiency columns
## FOR WASFI TO WORK WITH

In [ ]:
import pandas as pd
df=pd.read_excel("/content/Fifteen_minutes_merged_MEMR_data.xlsx")
df

,datetime,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file
0,2020-03-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.882214,0.0,12.422857,0.0,March 2020 Fixed.xlsx
1,2020-03-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.042200,0.0,11.410667,0.0,March 2020 Fixed.xlsx
2,2020-03-01 00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.621000,0.0,11.336000,0.0,March 2020 Fixed.xlsx
3,2020-03-01 00:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.347733,0.0,11.243333,0.0,March 2020 Fixed.xlsx
4,2020-03-01 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.290000,0.0,11.357333,0.0,March 2020 Fixed.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64325,2021-12-31 22:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.448867,0.0,12.984000,0.0,December 2021 fixed.xlsx
64326,2021-12-31 23:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.248933,0.0,12.978667,0.0,December 2021 fixed.xlsx
64327,2021-12-31 23:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.447800,0.0,12.892667,0.0,December 2021 fixed.xlsx
64328,2021-12-31 23:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.957800,0.0,12.940667,0.0,December 2021 fixed.xlsx
64329,2021-12-31 23:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.998300,0.0,12.639000,0.0,December 2021 fixed.xlsx

In [ ]:
AREA = 60000  # m²
gamma = -0.004  # temperature coefficient (per °C)
T_ref = 25  # reference temperature

# Convert energy → power

# The generated yield represents the *energy output over each 15-minute interval*, not instantaneous power. Therefore, I convert it to power by dividing by the time interval (0.25 hours) before applying physical equations.

In [ ]:
# 15 minutes = 0.25 hour
df["power_kw"] = df["generated_yield"] / 0.25

In [ ]:
df.head(50)

,datetime,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file,power_kw
0,2020-03-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.882214,0.000000,12.422857,0.000000,March 2020 Fixed.xlsx,0.000000
1,2020-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.042200,0.000000,11.410667,0.000000,March 2020 Fixed.xlsx,0.000000
2,2020-03-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.621000,0.000000,11.336000,0.000000,March 2020 Fixed.xlsx,0.000000
3,2020-03-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.347733,0.000000,11.243333,0.000000,March 2020 Fixed.xlsx,0.000000
4,2020-03-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.290000,0.000000,11.357333,0.000000,March 2020 Fixed.xlsx,0.000000
5,2020-03-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.246733,0.000000,11.379333,0.000000,March 2020 Fixed.xlsx,0.000000
6,2020-03-01 01:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.623333,0.000000,11.286000,0.000000,March 2020 Fixed.xlsx,0.000000
7,2020-03-01 01:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.674533,0.000000,10.998000,0.000000,March 2020 Fixed.xlsx,0.000000
8,2020-03-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.956800,0.000000,11.344667,0.000000,March 2020 Fixed.xlsx,0.000000
9,2020-03-01 02:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.073333,0.000000,12.028000,0.000000,March 2020 Fixed.xlsx,0.000000
10,2020-03-01 02:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.924400,0.000000,12.210667,0.000000,March 2020 Fixed.xlsx,0.000000
11,2020-03-01 02:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.277800,0.000000,12.088667,0.000000,March 2020 Fixed.xlsx,0.000000
12,2020-03-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.416600,0.000000,11.672000,0.000000,March 2020 Fixed.xlsx,0.000000
13,2020-03-01 03:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.644400,0.000000,10.570000,0.000000,March 2020 Fixed.xlsx,0.000000
14,2020-03-01 03:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.031133,0.000000,9.430000,0.000000,March 2020 Fixed.xlsx,0.000000
15,2020-03-01 03:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.318867,0.000000,10.122000,0.000000,March 2020 Fixed.xlsx,0.000000
16,2020-03-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.520000,0.000000,11.012000,0.000000,March 2020 Fixed.xlsx,0.000000
17,2020-03-01 04:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.238933,0.000000,10.923333,0.000000,March 2020 Fixed.xlsx,0.000000
18,2020-03-01 04:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.498933,0.000000,9.933333,0.000000,March 2020 Fixed.xlsx,0.000000
19,2020-03-01 04:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.544400,0.000000,9.324667,0.000000,March 2020 Fixed.xlsx,0.000000
20,2020-03-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.693400,0.000000,9.362000,0.000000,March 2020 Fixed.xlsx,0.000000
21,2020-03-01 05:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.482133,0.000000,10.558000,0.000000,March 2020 Fixed.xlsx,0.000000
22,2020-03-01 05:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.013333,0.000000,14.406667,0.000000,9.998000,0.002222,March 2020 Fixed.xlsx,0.000000
23,2020-03-01 05:45:00,1.360000,1.086667,1.046667,1.760000,1.380000,1.806667,1.012222,19.172200,0.000000,9.439333,1.406667,March 2020 Fixed.xlsx,0.000000
24,2020-03-01 06:00:00,6.886667,6.753333,6.740000,8.153333,7.526667,8.166667,7.371111,-6.968933,8.701133,9.709333,7.371111,March 2020 Fixed.xlsx,34.804533
25,2020-03-01 06:15:00,15.026667,14.766667,14.853333,16.513333,15.580000,16.433333,15.528889,-45.362267,45.362267,10.086000,15.528889,March 2020 Fixed.xlsx,181.449067
26,2020-03-01 06:30:00,33.853333,33.333333,34.280000,35.440000,34.366667,34.753333,34.337778,-133.834333,133.834333,10.289333,34.337778,March 2020 Fixed.xlsx,535.337333
27,2020-03-01 06:45:00,53.780000,53.593333,54.726667,56.180000,55.013333,55.453333,54.791111,-238.697733,238.697733,10.303333,54.791111,March 2020 Fixed.xlsx,954.790933
28,2020-03-01 07:00:00,164.833333,187.173333,173.033333,181.986667,196.573333,196.866667,183.411111,-1005.548800,1005.548800,10.870667,183.411111,March 2020 Fixed.xlsx,4022.195200
29,2020-03-01 07:15:00,176.626667,191.593333,184.380000,196.013333,205.086667,204.946667,193.107778,-1075.952200,1075.952200,13.308000,193.107778,March 2020 Fixed.xlsx,4303.808800
30,2020-03-01 07:30:00,204.706667,219.233333,211.733333,219.340000,227.060000,230.486667,218.760000,-1206.470000,1206.470000,12.410000,218.760000,March 2020 Fixed.xlsx,4825.880000
31,2020-03-01 07:45:00,201.553333,210.140000,209.353333,211.440000,217.340000,214.093333,210.653333,-1143.272200,1143.272200,14.620667,210.653333,March 2020 Fixed.xlsx,4573.088800
32,2020-03-01 08:00:00,393.940000,421.213333,402.193333,404.320000,426.426667,422.673333,411.794444,-2330.172733,2330.172733,15.560000,411.794444,March 2020 Fixed.xlsx,9320.690933
33,2020-03-01 08:15:00,535.406667,574.586667,546.266667,559.593333,582.980000,592.880000,565.285556,-3241.308867,3241.308867,17.384000,565.285556,March 2020 Fixed.xlsx,12965.235467
34,2020-03-01 08:30:00,599.146667,638.033333,606.726667,617.806667,639.886667,652.433333,625.672222,-3573.920067,3573.920067,17.929333,625.672222,March 2020 Fixed.xlsx,14295.680267
35,2020-03-01 08:45:00,654.113333,686.486667,654.026667,674.206667,687.226667,709.433333,677.582222,-3848.891000,3848.891000,18.650000,677.582222,March 2020 Fixed.xlsx,15395.564000
36,2020-03-01 09:00:00,721.873333,761.473333,727.593333,737.026667,756.280000,772.413333,746.110000,-4208.572267,4208.572267,19.200667,746.110000,March 2020 Fixed.xlsx,16834.289067
37,2020-03-01 09:15:00,746.020000,778.340000,747.333333,758.526667,777.486667,796.473333,767.363333,-4290.062200,4290.062200,19.637333,767.363333,March 2020 Fixed.xlsx,17160.248800
38,2020-03-01 09:30:00,823.213333,856.733333,821.206667,819.026667,837.633333,848.806667,834.436667,-4671.145600,4671.145600,20.432667,834.436667,March 2020 Fixed.xlsx,18684.582400
39,2020-03-01 09:45:00,862.226667,889.053333,853.726667,868.933333,884.113333,905.220000,877.212222,-4875.581067,4875.581067,21.175333,877.212222,March 2020 Fixed.xlsx,19502.324267
40,2020-03-01 10:00:00,895.260000,922.286667,889.346667,887.406667,902.326667,928.153333,904.130000,-4960.336600,4960.336600,21.886000,904.130000,March 2020 Fixed.xlsx,19841.346400
41,2020-03-01 10:15:00,923.486667,953.133333,915.740000,915.260000,928.466667,952.620000,931.451111,-4975.190000,4975.190000,22.397333,931.451111,March 2020 Fixed.xlsx,19900.760000
42,2020-03-01 10:30:00,912.346667,952.420000,919.646667,917.420000,925.933333,961.893333,931.610000,-4800.294533,4800.294533,22.908667,931.610000,March 2020 Fixed.xlsx,19201.178133
43,2020-03-01 10:45:00,883.880000,907.206667,877.880000,871.066667,880.766667,893.753333,885.758889,-4429.727667,4429.727667,23.558000,885.758889,March 2020 Fixed.xlsx,17718.910667
44,2020-03-01 11:00:00,986.920000,1012.100000,971.653333,969.273333,976.113333,1012.320000,988.063333,-4943.606667,4943.606667,23.596667,988.063333,March 2020 Fixed.xlsx,19774.426667
45,2020-03-01 11:15:00,736.586667,763.906667,732.306667,733.913333,755.320000,779.433333,750.244444,-3669.942200,3669.942200,23.549333,750.244444,March 2020 Fixed.xlsx,14679.768800
46,2020-03-01 11:30:00,997.700000,1017.353333,986.533333,958.706667,975.180000,985.926667,986.900000,-4811.971133,4811.971133,23.065333,986.900000,March 2020 Fixed.xlsx,19247.884533
47,2020-03-01 11:45:00,989.213333,1020.766667,974.080000,968.126667,969.760000,1008.113333,988.343333,-4868.484467,4868.484467,24.742000,988.343333,March 2020 Fixed.xlsx,19473.937867
48,2020-03-01 12:00:00,978.866667,987.973333,951.080000,955.506667,948.426667,990.133333,968.664444,-4738.810000,4738.810000,25.074667,968.664444,March 2020 Fixed.xlsx,18955.240000
49,2020-03-01 12:15:00,1019.960000,1025.506667,986.313333,978.313333,978.613333,1016.646667,1000.892222,-4978.542267,4978.542267,25.155333,1000.892222,March 2020 Fixed.xlsx,19914.169067

#  FIX UNITS (VERY IMPORTANT)

irradiance is in W/m², and power is in kW

convert irradiance to kW/m²

In [ ]:
df["irradiance_kw_m2"] = df["irradiance_avg"] / 1000

# Compute efficiency correctly 𝜂=𝑃/𝐺×𝐴

In [ ]:

df["efficiency"] = df["power_kw"] / (
    df["irradiance_kw_m2"] * AREA
)

In [ ]:
df.head(50)

,datetime,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file,power_kw,irradiance_kw_m2,efficiency
0,2020-03-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.882214,0.000000,12.422857,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
1,2020-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.042200,0.000000,11.410667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
2,2020-03-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.621000,0.000000,11.336000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
3,2020-03-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.347733,0.000000,11.243333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
4,2020-03-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.290000,0.000000,11.357333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
5,2020-03-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.246733,0.000000,11.379333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
6,2020-03-01 01:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.623333,0.000000,11.286000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
7,2020-03-01 01:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.674533,0.000000,10.998000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
8,2020-03-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.956800,0.000000,11.344667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
9,2020-03-01 02:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.073333,0.000000,12.028000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
10,2020-03-01 02:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.924400,0.000000,12.210667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
11,2020-03-01 02:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.277800,0.000000,12.088667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
12,2020-03-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.416600,0.000000,11.672000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
13,2020-03-01 03:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.644400,0.000000,10.570000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
14,2020-03-01 03:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.031133,0.000000,9.430000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
15,2020-03-01 03:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.318867,0.000000,10.122000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
16,2020-03-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.520000,0.000000,11.012000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
17,2020-03-01 04:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.238933,0.000000,10.923333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
18,2020-03-01 04:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.498933,0.000000,9.933333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
19,2020-03-01 04:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.544400,0.000000,9.324667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
20,2020-03-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.693400,0.000000,9.362000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
21,2020-03-01 05:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.482133,0.000000,10.558000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN
22,2020-03-01 05:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.013333,0.000000,14.406667,0.000000,9.998000,0.002222,March 2020 Fixed.xlsx,0.000000,0.000002,0.000000
23,2020-03-01 05:45:00,1.360000,1.086667,1.046667,1.760000,1.380000,1.806667,1.012222,19.172200,0.000000,9.439333,1.406667,March 2020 Fixed.xlsx,0.000000,0.001407,0.000000
24,2020-03-01 06:00:00,6.886667,6.753333,6.740000,8.153333,7.526667,8.166667,7.371111,-6.968933,8.701133,9.709333,7.371111,March 2020 Fixed.xlsx,34.804533,0.007371,0.118044
25,2020-03-01 06:15:00,15.026667,14.766667,14.853333,16.513333,15.580000,16.433333,15.528889,-45.362267,45.362267,10.086000,15.528889,March 2020 Fixed.xlsx,181.449067,0.015529,0.292115
26,2020-03-01 06:30:00,33.853333,33.333333,34.280000,35.440000,34.366667,34.753333,34.337778,-133.834333,133.834333,10.289333,34.337778,March 2020 Fixed.xlsx,535.337333,0.034338,0.389758
27,2020-03-01 06:45:00,53.780000,53.593333,54.726667,56.180000,55.013333,55.453333,54.791111,-238.697733,238.697733,10.303333,54.791111,March 2020 Fixed.xlsx,954.790933,0.054791,0.435650
28,2020-03-01 07:00:00,164.833333,187.173333,173.033333,181.986667,196.573333,196.866667,183.411111,-1005.548800,1005.548800,10.870667,183.411111,March 2020 Fixed.xlsx,4022.195200,0.183411,0.548249
29,2020-03-01 07:15:00,176.626667,191.593333,184.380000,196.013333,205.086667,204.946667,193.107778,-1075.952200,1075.952200,13.308000,193.107778,March 2020 Fixed.xlsx,4303.808800,0.193108,0.557177
30,2020-03-01 07:30:00,204.706667,219.233333,211.733333,219.340000,227.060000,230.486667,218.760000,-1206.470000,1206.470000,12.410000,218.760000,March 2020 Fixed.xlsx,4825.880000,0.218760,0.551504
31,2020-03-01 07:45:00,201.553333,210.140000,209.353333,211.440000,217.340000,214.093333,210.653333,-1143.272200,1143.272200,14.620667,210.653333,March 2020 Fixed.xlsx,4573.088800,0.210653,0.542727
32,2020-03-01 08:00:00,393.940000,421.213333,402.193333,404.320000,426.426667,422.673333,411.794444,-2330.172733,2330.172733,15.560000,411.794444,March 2020 Fixed.xlsx,9320.690933,0.411794,0.565858
33,2020-03-01 08:15:00,535.406667,574.586667,546.266667,559.593333,582.980000,592.880000,565.285556,-3241.308867,3241.308867,17.384000,565.285556,March 2020 Fixed.xlsx,12965.235467,0.565286,0.573393
34,2020-03-01 08:30:00,599.146667,638.033333,606.726667,617.806667,639.886667,652.433333,625.672222,-3573.920067,3573.920067,17.929333,625.672222,March 2020 Fixed.xlsx,14295.680267,0.625672,0.571213
35,2020-03-01 08:45:00,654.113333,686.486667,654.026667,674.206667,687.226667,709.433333,677.582222,-3848.891000,3848.891000,18.650000,677.582222,March 2020 Fixed.xlsx,15395.564000,0.677582,0.568033
36,2020-03-01 09:00:00,721.873333,761.473333,727.593333,737.026667,756.280000,772.413333,746.110000,-4208.572267,4208.572267,19.200667,746.110000,March 2020 Fixed.xlsx,16834.289067,0.746110,0.564069
37,2020-03-01 09:15:00,746.020000,778.340000,747.333333,758.526667,777.486667,796.473333,767.363333,-4290.062200,4290.062200,19.637333,767.363333,March 2020 Fixed.xlsx,17160.248800,0.767363,0.559065
38,2020-03-01 09:30:00,823.213333,856.733333,821.206667,819.026667,837.633333,848.806667,834.436667,-4671.145600,4671.145600,20.432667,834.436667,March 2020 Fixed.xlsx,18684.582400,0.834437,0.559796
39,2020-03-01 09:45:00,862.226667,889.053333,853.726667,868.933333,884.113333,905.220000,877.212222,-4875.581067,4875.581067,21.175333,877.212222,March 2020 Fixed.xlsx,19502.324267,0.877212,0.555804
40,2020-03-01 10:00:00,895.260000,922.286667,889.346667,887.406667,902.326667,928.153333,904.130000,-4960.336600,4960.336600,21.886000,904.130000,March 2020 Fixed.xlsx,19841.346400,0.904130,0.548631
41,2020-03-01 10:15:00,923.486667,953.133333,915.740000,915.260000,928.466667,952.620000,931.451111,-4975.190000,4975.190000,22.397333,931.451111,March 2020 Fixed.xlsx,19900.760000,0.931451,0.534133
42,2020-03-01 10:30:00,912.346667,952.420000,919.646667,917.420000,925.933333,961.893333,931.610000,-4800.294533,4800.294533,22.908667,931.610000,March 2020 Fixed.xlsx,19201.178133,0.931610,0.515269
43,2020-03-01 10:45:00,883.880000,907.206667,877.880000,871.066667,880.766667,893.753333,885.758889,-4429.727667,4429.727667,23.558000,885.758889,March 2020 Fixed.xlsx,17718.910667,0.885759,0.500105
44,2020-03-01 11:00:00,986.920000,1012.100000,971.653333,969.273333,976.113333,1012.320000,988.063333,-4943.606667,4943.606667,23.596667,988.063333,March 2020 Fixed.xlsx,19774.426667,0.988063,0.500333
45,2020-03-01 11:15:00,736.586667,763.906667,732.306667,733.913333,755.320000,779.433333,750.244444,-3669.942200,3669.942200,23.549333,750.244444,March 2020 Fixed.xlsx,14679.768800,0.750244,0.489166
46,2020-03-01 11:30:00,997.700000,1017.353333,986.533333,958.706667,975.180000,985.926667,986.900000,-4811.971133,4811.971133,23.065333,986.900000,March 2020 Fixed.xlsx,19247.884533,0.986900,0.487584
47,2020-03-01 11:45:00,989.213333,1020.766667,974.080000,968.126667,969.760000,1008.113333,988.343333,-4868.484467,4868.484467,24.742000,988.343333,March 2020 Fixed.xlsx,19473.937867,0.988343,0.492590
48,2020-03-01 12:00:00,978.866667,987.973333,951.080000,955.506667,948.426667,990.133333,968.664444,-4738.810000,4738.810000,25.074667,968.664444,March 2020 Fixed.xlsx,18955.240000,0.968664,0.489211
49,2020-03-01 12:15:00,1019.960000,1025.506667,986.313333,978.313333,978.613333,1016.646667,1000.892222,-4978.542267,4978.542267,25.155333,1000.892222,March 2020 Fixed.xlsx,19914.169067,1.000892,0.497410

# The 50 W/m² threshold is used to remove unstable efficiency values, , The usage of values such as 20 or so will add low irradiance values to  that denominator that explode the values of the efficiency and affect the reference efficiency

In [ ]:
df.loc[df["irradiance_avg"] < 50, "efficiency"] = pd.NA
df["efficiency"] = df["efficiency"].clip(lower=0, upper=1)

# 200 W/m² threshold is used to ensure that reference efficiency is calculated only from high-quality, stable operating conditions.Since the basline effieciency should be presented with the best values as it is the bottle neck of optiminmzing the system and conducting analysis.

In [ ]:
eta_ref = df[df["irradiance_avg"] > 200]["efficiency"].mean()
print("η_ref =", eta_ref)

η_ref = 0.4896457518423524

# Apply physical model 𝑃 = 𝐺 × 𝐴 × 𝜂𝑟𝑒𝑓 × (1+𝛾(𝑇−25))

# Why 25°C is used as the reference temperature?

25°C is the Standard Test Condition (STC) temperature used in almost all PV datasheets.

At STC:

Irradiance = 1000 W/m²
Cell temperature = 25°C
Spectrum = AM1.5

So when manufacturers give:

𝑃𝑆𝑇𝐶  (rated power)
 it is always at 25°C, so models use it as the baseline reference.

That’s why in the power equation we compare actual temperature to 25°C:


**(
𝑇
𝑐
𝑒
𝑙
𝑙
−
25
)**

It represents:
👉 “How far are we from ideal rated conditions?”

# Why gamma = -0.004?

This is the temperature coefficient of power.

Typical silicon solar panels have:

𝛾
≈
−
0.003
γ≈−0.003 to
−
0.005
−0.005 per °C

A very common “standard average” used in research is:

𝛾 =− 0.004
/
∘
𝐶


Meaning:

For every 1°C increase above 25°C → power decreases by ~0.4%
3) Why negative?

Because solar panels:

lose efficiency when temperature rises
electrons recombine more easily at higher temperature
voltage drops significantly

So:

𝑃
↓
 when
𝑇
↑

In [ ]:
gamma = -0.004
T_ref = 25

df["predicted_power_kw"] = (
    df["irradiance_kw_m2"]
    * AREA
    * eta_ref
    * (1 + gamma * (df["avg_module_temp"] - T_ref))
)

# Convert power → energy (back to 15-min)

In [ ]:
df["predicted_yield_physical"] = df["predicted_power_kw"] * 0.25

In [ ]:
df.head(50)

,datetime,irr_sensor_1,irr_sensor_2,irr_sensor_3,irr_sensor_4,irr_sensor_5,irr_sensor_6,irradiation_tilted,power_analyzer,generated_yield,avg_module_temp,irradiance_avg,source_file,power_kw,irradiance_kw_m2,efficiency,predicted_power_kw,predicted_yield_physical
0,2020-03-01 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.882214,0.000000,12.422857,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
1,2020-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.042200,0.000000,11.410667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
2,2020-03-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.621000,0.000000,11.336000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
3,2020-03-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.347733,0.000000,11.243333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
4,2020-03-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.290000,0.000000,11.357333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
5,2020-03-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.246733,0.000000,11.379333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
6,2020-03-01 01:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.623333,0.000000,11.286000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
7,2020-03-01 01:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.674533,0.000000,10.998000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
8,2020-03-01 02:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.956800,0.000000,11.344667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
9,2020-03-01 02:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.073333,0.000000,12.028000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
10,2020-03-01 02:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.924400,0.000000,12.210667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
11,2020-03-01 02:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.277800,0.000000,12.088667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
12,2020-03-01 03:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.416600,0.000000,11.672000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
13,2020-03-01 03:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.644400,0.000000,10.570000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
14,2020-03-01 03:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.031133,0.000000,9.430000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
15,2020-03-01 03:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.318867,0.000000,10.122000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
16,2020-03-01 04:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.520000,0.000000,11.012000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
17,2020-03-01 04:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.238933,0.000000,10.923333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
18,2020-03-01 04:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.498933,0.000000,9.933333,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
19,2020-03-01 04:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.544400,0.000000,9.324667,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
20,2020-03-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.693400,0.000000,9.362000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
21,2020-03-01 05:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.482133,0.000000,10.558000,0.000000,March 2020 Fixed.xlsx,0.000000,0.000000,NaN,0.000000,0.000000
22,2020-03-01 05:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.013333,0.000000,14.406667,0.000000,9.998000,0.002222,March 2020 Fixed.xlsx,0.000000,0.000002,NaN,0.046136,0.011534
23,2020-03-01 05:45:00,1.360000,1.086667,1.046667,1.760000,1.380000,1.806667,1.012222,19.172200,0.000000,9.439333,1.406667,March 2020 Fixed.xlsx,0.000000,0.001407,NaN,29.265565,7.316391
24,2020-03-01 06:00:00,6.886667,6.753333,6.740000,8.153333,7.526667,8.166667,7.371111,-6.968933,8.701133,9.709333,7.371111,March 2020 Fixed.xlsx,34.804533,0.007371,NaN,153.199343,38.299836
25,2020-03-01 06:15:00,15.026667,14.766667,14.853333,16.513333,15.580000,16.433333,15.528889,-45.362267,45.362267,10.086000,15.528889,March 2020 Fixed.xlsx,181.449067,0.015529,NaN,322.290323,80.572581
26,2020-03-01 06:30:00,33.853333,33.333333,34.280000,35.440000,34.366667,34.753333,34.337778,-133.834333,133.834333,10.289333,34.337778,March 2020 Fixed.xlsx,535.337333,0.034338,NaN,712.107568,178.026892
27,2020-03-01 06:45:00,53.780000,53.593333,54.726667,56.180000,55.013333,55.453333,54.791111,-238.697733,238.697733,10.303333,54.791111,March 2020 Fixed.xlsx,954.790933,0.054791,0.435650,1136.215092,284.053773
28,2020-03-01 07:00:00,164.833333,187.173333,173.033333,181.986667,196.573333,196.866667,183.411111,-1005.548800,1005.548800,10.870667,183.411111,March 2020 Fixed.xlsx,4022.195200,0.183411,0.548249,3795.283747,948.820937
29,2020-03-01 07:15:00,176.626667,191.593333,184.380000,196.013333,205.086667,204.946667,193.107778,-1075.952200,1075.952200,13.308000,193.107778,March 2020 Fixed.xlsx,4303.808800,0.193108,0.557177,3959.060934,989.765234
30,2020-03-01 07:30:00,204.706667,219.233333,211.733333,219.340000,227.060000,230.486667,218.760000,-1206.470000,1206.470000,12.410000,218.760000,March 2020 Fixed.xlsx,4825.880000,0.218760,0.551504,4500.368451,1125.092113
31,2020-03-01 07:45:00,201.553333,210.140000,209.353333,211.440000,217.340000,214.093333,210.653333,-1143.272200,1143.272200,14.620667,210.653333,March 2020 Fixed.xlsx,4573.088800,0.210653,0.542727,4297.113452,1074.278363
32,2020-03-01 08:00:00,393.940000,421.213333,402.193333,404.320000,426.426667,422.673333,411.794444,-2330.172733,2330.172733,15.560000,411.794444,March 2020 Fixed.xlsx,9320.690933,0.411794,0.565858,8369.883102,2092.470776
33,2020-03-01 08:15:00,535.406667,574.586667,546.266667,559.593333,582.980000,592.880000,565.285556,-3241.308867,3241.308867,17.384000,565.285556,March 2020 Fixed.xlsx,12965.235467,0.565286,0.573393,11408.871656,2852.217914
34,2020-03-01 08:30:00,599.146667,638.033333,606.726667,617.806667,639.886667,652.433333,625.672222,-3573.920067,3573.920067,17.929333,625.672222,March 2020 Fixed.xlsx,14295.680267,0.625672,0.571213,12600.894386,3150.223597
35,2020-03-01 08:45:00,654.113333,686.486667,654.026667,674.206667,687.226667,709.433333,677.582222,-3848.891000,3848.891000,18.650000,677.582222,March 2020 Fixed.xlsx,15395.564000,0.677582,0.568033,13608.093926,3402.023482
36,2020-03-01 09:00:00,721.873333,761.473333,727.593333,737.026667,756.280000,772.413333,746.110000,-4208.572267,4208.572267,19.200667,746.110000,March 2020 Fixed.xlsx,16834.289067,0.746110,0.564069,14952.170569,3738.042642
37,2020-03-01 09:15:00,746.020000,778.340000,747.333333,758.526667,777.486667,796.473333,767.363333,-4290.062200,4290.062200,19.637333,767.363333,March 2020 Fixed.xlsx,17160.248800,0.767363,0.559065,15351.839527,3837.959882
38,2020-03-01 09:30:00,823.213333,856.733333,821.206667,819.026667,837.633333,848.806667,834.436667,-4671.145600,4671.145600,20.432667,834.436667,March 2020 Fixed.xlsx,18684.582400,0.834437,0.559796,16641.712937,4160.428234
39,2020-03-01 09:45:00,862.226667,889.053333,853.726667,868.933333,884.113333,905.220000,877.212222,-4875.581067,4875.581067,21.175333,877.212222,March 2020 Fixed.xlsx,19502.324267,0.877212,0.555804,17443.774837,4360.943709
40,2020-03-01 10:00:00,895.260000,922.286667,889.346667,887.406667,902.326667,928.153333,904.130000,-4960.336600,4960.336600,21.886000,904.130000,March 2020 Fixed.xlsx,19841.346400,0.904130,0.548631,17928.709093,4482.177273
41,2020-03-01 10:15:00,923.486667,953.133333,915.740000,915.260000,928.466667,952.620000,931.451111,-4975.190000,4975.190000,22.397333,931.451111,March 2020 Fixed.xlsx,19900.760000,0.931451,0.534133,18433.167508,4608.291877
42,2020-03-01 10:30:00,912.346667,952.420000,919.646667,917.420000,925.933333,961.893333,931.610000,-4800.294533,4800.294533,22.908667,931.610000,March 2020 Fixed.xlsx,19201.178133,0.931610,0.515269,18398.991998,4599.747999
43,2020-03-01 10:45:00,883.880000,907.206667,877.880000,871.066667,880.766667,893.753333,885.758889,-4429.727667,4429.727667,23.558000,885.758889,March 2020 Fixed.xlsx,17718.910667,0.885759,0.500105,17448.388212,4362.097053
44,2020-03-01 11:00:00,986.920000,1012.100000,971.653333,969.273333,976.113333,1012.320000,988.063333,-4943.606667,4943.606667,23.596667,988.063333,March 2020 Fixed.xlsx,19774.426667,0.988063,0.500333,19460.670003,4865.167501
45,2020-03-01 11:15:00,736.586667,763.906667,732.306667,733.913333,755.320000,779.433333,750.244444,-3669.942200,3669.942200,23.549333,750.244444,March 2020 Fixed.xlsx,14679.768800,0.750244,0.489166,14779.425516,3694.856379
46,2020-03-01 11:30:00,997.700000,1017.353333,986.533333,958.706667,975.180000,985.926667,986.900000,-4811.971133,4811.971133,23.065333,986.900000,March 2020 Fixed.xlsx,19247.884533,0.986900,0.487584,19478.838367,4869.709592
47,2020-03-01 11:45:00,989.213333,1020.766667,974.080000,968.126667,969.760000,1008.113333,988.343333,-4868.484467,4868.484467,24.742000,988.343333,March 2020 Fixed.xlsx,19473.937867,0.988343,0.492590,19377.501547,4844.375387
48,2020-03-01 12:00:00,978.866667,987.973333,951.080000,955.506667,948.426667,990.133333,968.664444,-4738.810000,4738.810000,25.074667,968.664444,March 2020 Fixed.xlsx,18955.240000,0.968664,0.489211,18966.430874,4741.607719
49,2020-03-01 12:15:00,1019.960000,1025.506667,986.313333,978.313333,978.613333,1016.646667,1000.892222,-4978.542267,4978.542267,25.155333,1000.892222,March 2020 Fixed.xlsx,19914.169067,1.000892,0.497410,19591.124800,4897.781200

In [ ]:
import pandas as pd

# File paths (change these to your actual file names)
file1 = "/content/Fifteen_minutes_merged_MEMR_data.xlsx"   # First file: 2020–2021
file2 = "/content/Fifteen_minutes_merged_2022_data.xlsx"        # Second file: 2022

# Read both Excel files
df1 = pd.read_excel(file1)
df2 = pd.read_excel(file2)

# Concatenate vertically (one on top of the other)
df_combined = pd.concat([df1, df2], axis=0, ignore_index=True)

# Optional: sort by datetime column if needed
# Replace 'DateTime' with your actual datetime column name
df_combined['datetime'] = pd.to_datetime(df_combined['datetime'])
df_combined = df_combined.sort_values(by='datetime')

# Save the combined file
output_file = "Fifteen_minutes_merged_2020-2022.xlsx"
df_combined.to_excel(output_file, index=False)

print(f"Files successfully combined and saved as: {output_file}")
print(f"Total rows: {len(df_combined)}")

Files successfully combined and saved as: Fifteen_minutes_merged_2020-2022.xlsx
Total rows: 69610